# pixSync config file

max_retry: 3
restrict:
  - "public"
  - "private"
savepath: "./download"
dbpath: "db.json"

naming_rule: "{id}_{title}" # default "{id}"

# extra_request_params

# proxies:
#   http: "http://127.0.0.1:7890"
#   https: "http://127.0.0.1:7890"